outros_rendimentos_dic = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "tipo_situacao",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "unidade_consumo",
    "COD_INFORMANTE": "codigo_informante",
    "QUADRO": "registro_rendimento",
    "SEQ": "sequencial_linha",
    "V9001": "tipo_rendimento",
    "V8500": "rendimento_bruto",
    "V8501": "deducao_rendimento",
    "V9010": "mes_rendimento",
    "V9011": "periodo_rendimento",
    "DEFLATOR": "fator_deflator",
    "V8500_DEFLA": "rendimento_deflacionado",
    "V8501_DEFLA": "deducao_deflacionada",
    "COD_IMPUT_VALOR": "imputacao_rendimento",
    "FATOR_ANUALIZACAO": "fator_anualizacao",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "rendimento_total"
}

aluguel_estimado_dic = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "tipo_domicilio",
    "COD_UPA": "codigo_amostragem",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numeroconsumo",
    "QUADRO": "codigo_despesa",
    "V9001": "codigo_despesa_fixo",
    "V9002": "forma_aquisicao",
    "V8000": "valor_aluguel",
    "V9010": "mes_despesa",
    "V9011": "duracao_despesa",
    "DEFLATOR": "fator_deflacionario",
    "V8000_DEFLA": "aluguel_deflacionado",
    "COD_IMPUT_VALOR": "imputacao_valor",
    "FaTOR_ANUALIZACAO": "fator_anualizacao",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_total_uc"
}

caderneta_coletiva_dic = {
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "situacao_domicilio",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numero_consumo",
    "QUADRO": "numero_quadro",
    "SEQ": "sequencial_linha",
    "V9001": "codigo_despesa",
    "V9002": "modalidade_aquisicao",
    "V8000": "valor_despesa",
    "DEFLATOR": "fator_deflacionario",
    "V8000_DEFLA": "despesa_deflacionada",
    "COD_IMPUT_VALOR": "imputacao_valor",
    "FATOR_ANUALIZACAO": "fator_semanal",
    "PESO": "fator_expansao_upa",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_uc",
    "V9005": "quantidade_adquirida",
    "V9007": "codigo_unidade_medida",
    "V9009": "codigo_peso_volume",
    "QTD_FINAL": "quantidade_final_kg"
}

despesa_individual_dic = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostra",
    "TIPO_SITUACAO_REG": "situacao_domiciliar",
    "COD_UPA": "codigo_amostragem",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numero_uc",
    "COD_INFORMANTE": "codigo_informante",
    "QUADRO": "numero_quadro",
    "SEQ": "sequencial_linha",
    "V9001": "codigo_despesa",
    "V9002": "forma_aquisicao",
    "V8000": "valor_despesa",
    "V9010": "mes_ultima_despesa",
    "V9011": "duracao_despesa",
    "V9012": "estado_produto",
    "V4104": "motivo_viagem",
    "V4105": "origem_despesa",
    "DEFLATOR": "fator_deflacionario",
    "V8000_DEFLA": "despesa_deflacionada",
    "COD_IMPUT_VALOR": "imputacao_valor",
    "FATOR_ANUALIZACAO": "fator_anualizacao",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_uc",
    "V9004": "local_aquisicao"
}

despesa_coletiva_dic = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "situacao_domiciliar",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numero_uc",
    "COD_INFORMANTE": "codigo_informante",
    "QUADRO": "quadro_despesa",
    "SEQ": "sequencial_linha",
    "V9001": "codigo_despesa",
    "V9002": "forma_aquisicao",
    "V9005": "quantidade_kwh",
    "V8000": "valor_despesa",
    "V9010": "mes_ultima_despesa",
    "V9011": "duracao_despesa",
    "V9012": "estado_produto",
    "V1904": "despesa_inss",
    "V1905": "tipo_servico_domestico",
    "DEFLATOR": "fator_deflacionario",
    "V8000_DEFLA": "despesas_deflacionada",
    "V1904_DEFLA": "inss_deflacionado",
    "COD_IMPUT_VALOR": "imputacao_valor",
    "COD_IMPUT_QUANTIDADE": "imputacao_quantidade_kwh",
    "FATOR_ANUALIZACAO": "fator_anualizacao",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_uc",
    "V9004": "local_aquisicao"
}

domicilio_dic = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "situacao_domiciliar",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domicilio",
    "V0201": "tipo_domicilio",
    "V0202": "material_paredes",
    "V0203": "material_cobertura",
    "V0204": "material_piso",
    "V0205": "total_comodos",
    "V0206": "comodos_dormitorios",
    "V0207": "abastecimento_agua",
    "V0208": "disponibilidade_agua",
    "V0209": "aquecimento_agua",
    "V02105": "instalacoes_sanitarias",
    "V02111": "escoadouro_banheiro",
    "V02113": "destino_lixo",
    "V0212": "fonte_energia_eletrica",
    "V0213": "frequencia_eletrecidade",
    "V02141": "combustivel_alimentos",
    "V02142": "situacao_domicilio",
    "V0215": "tipo_contratual_aluguel",
    "V02161": "pavimentacao_rua",
    "V02164": "servico_correios",
    "V0217": "fator_expansao",
    "V0219": "peso_ajustado",
    "V0220": "seguranca_alimentar",
    "V0221": "seguranca_alimentar",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "V6199": "seguranca_alimentar"
}

inventario_dic = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "situacao_domiciliar",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numero_uc",
    "QUADRO": "quadro_registro",
    "SEQ": "sequencial_linha",
    "V9001": "codigo_bem_duravel",
    "V9005": "quantidade_bem",
    "V9002": "forma_aquisicao_bem",
    "V1404": "ano_ultima_aquisicao",
    "V9012": "estado_aquisicao_bem",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_uc"
}

inventario_dic = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "situacao_domiciliar",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numero_uc",
    "QUADRO": "quadro_registro",
    "SEQ": "sequencial_linha",
    "V9001": "codigo_bem_duravel",
    "V9005": "quantidade_bem",
    "V9002": "forma_aquisicao_bem",
    "V1404": "ano_ultima_aquisicao",
    "V9012": "estado_aquisicao_bem",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_uc"
}

rendimento_trabalho = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "situacao_domiciliar",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domiciliar",
    "NUM_UC": "unidade_consumo",
    "COD_INFORMANTE": "codigo_informante",
    "QUADRO": "quadro_rendimento",
    "SUB_QUADRO": "subquadro_trabalho",
    "SEQ": "seq_registro",
    "V9001": "tipo_rendimento",
    "V5302": "natureza_trabalho",
    "V53021": "trabalhador_nao_remunerado",
    "V5303": "servidor_publico",
    "V5304": "carteira_assinada",
    "V5305": "contribuinte_previdencia",
    "V5307": "forma_pagamento",
    "V8500": "rendimento_bruto",
    "V531112": "deducao_previdencia",
    "V531122": "deducao_ir",
    "V531132": "deducao_iss_outros",
    "V9010": "mes_ultimo_rendimento",
    "V9011": "meses_rendimento_recebido",
    "V5314": "horas_semanais",
    "V5315": "deslocamento_trabalho",
    "DEFLATOR": "fator_deflacao",
    "V8500_DEFLA": "rendimento_ajustado",
    "V531112_DEFLA": "deducao_previdencia_ajustada",
    "V531122_DEFLA": "deducao_ir_ajustada",
    "V531132_DEFLA": "deducao_iss_ajustada",
    "COD_IMPUT_VALOR": "imputacao_rendimento",
    "FATOR_ANUALIZACAO": "anualizacao_rendimento",
    "PESO": "peso_amostral",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "rendimento_mensal",
    "V53011": "codigo_ocupacao",
    "V53061": "codigo_atividade"
}

restricao_produto_servicos_saude = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "situacao_domiciliar",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numero_uc",
    "COD_INFORMANTE": "codigo_informante",
    "QUADRO": "registro_despesa",
    "SEQ": "sequencial_linha",
    "V9001": "codigo_despesa",
    "V9013": "motivo_restricao",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_total"
}

servico_nao_monetario_pof2 = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "tipo_domicilio",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numero_uc",
    "QUADRO": "registro_despesa",
    "SEQ": "sequencial",
    "V9001": "codigo_despesa",
    "V9002": "metodo_aquisicao",
    "V8000": "valor_despesa",
    "V9010": "ultimo_mes_despesa",
    "V9011": "frequencia_despesa",
    "V1904": "despesa_inss",
    "V1905": "tipo_servico_domestico",
    "DEFLATOR": "fator_deflator",
    "V8000_DEFLA": "despesa_deflacionada",
    "V1904_DEFLA": "inss_deflacionado",
    "COD_IMPUT_VALOR": "imputacao_valor",
    "FATOR_ANUALIZACAO": "fator_anualizacao",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_total",
    "V9004": "local_aquisicao"
}

servico_nao_monetario_pof4 = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "tipo_de_domocilio",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domiciliar",
    "NUM_UC": "numero_uc",
    "COD_INFORMANTE": "codigo_informante",
    "QUADRO": "quadro_registro",
    "SEQ": "sequencial_linha",
    "V9001": "codigo_despesa_aquisicao",
    "V9002": "forma_aquisicao",
    "V8000": "valor_despesa_aquisicao",
    "V9010": "ultimo_mes_despesa",
    "V9011": "meses_despesa",
    "V4104": "motivo_viagem",
    "V4105": "origem_viagem",
    "DEFLATOR": "fator_deflacao",
    "V8000_DEFLA": "despesa_deflacionada",
    "COD_IMPUT_VALOR": "imputacao_valor",
    "FATOR_ANUALIZACAO": "fator_anualizacao",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_total",
    "V9004": "local_aquisicao"
}

consumo_alimentar = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "situacao_domiciliar",
    "COD_UPA": "codigo_amostral",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numero_uc",
    "COD_INFORMANTE": "codigo_informante",
    "QUADRO": "quadro_registro",
    "SEQ": "sequencial_linha",
    "V9005": "quantidade_consumida",
    "V9007": "codigo_unidade_medida",
    "V9001": "codigo_alimento",
    "V9015": "horario_consumo",
    "V9016": "codigo_preparacao",
    "V9017": "ocasiao_consumo",
    "V9018": "local_refeicao",
    "V9019": "adicao_de_azeite",
    "V9020": "adicao_de_manteiga",
    "V9021": "adicao_de_acucar",
    "V9022": "adicao_de_adoçante",
    "V9023": "adicao_de_mel",
    "V9024": "adicao_de_melado",
    "V9025": "adicao_de_maionese",
    "V9026": "adicao_de_ketchup",
    "V9027": "adicao_de_mostarda",
    "V9028": "adicao_de_shoyu",
    "V9029": "adicao_queijo_ralado",
    "V9030": "adicao_creme_leite",
    "COD_UNIDADE_MEDIDA_FINAL": "codigo_medida_final",
    "COD_PREPARACAO_FINAL": "codigo_preparacao_final",
    "GRAMATURA1": "gramatura_alimento",
    "QTD": "quantidade_gramas",
    "COD_TBCA": "codigo_tbca",
    "ENERGIA_KCAL ate ZINCO": "informacoes_nutricionais",
    "PESO": "fator_expansao",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_uc",
    "DIA_SEMANA": "dia_semana_consumo",
    "DIA_ATIPICO": "consumo_atipico"
}


condicoes_vida_dic = {
    "UF": "estado",
    "ESTRATO_POF": "estrato_amostral",
    "TIPO_SITUACAO_REG": "situacao_domicilio",
    "COD_UPA": "codigo_amostragem",
    "NUM_DOM": "numero_domicilio",
    "NUM_UC": "numero_consumo",
    "COD_INFORMANTE": "codigo_informante",
    "V6101": "avaliacao_rendimento",
    "V6102": "rendimento_necessario",
    "V6103": "custo_alimentacao",
    "V61041": "padrao_vida_alimentacao",
    "V61042": "padrao_vida_moradia",
    "V61043": "padrao_vida_vestuario",
    "V61044": "padrao_vida_educacao",
    "V61045": "padrao_vida_saude",
    "V61046": "padrao_vida_lazer",
    "V61051": "condicao_fornecimento_agua",
    "V61052": "condicao_energia_eletrica",
    "V61053": "condicao_iluminacao_rua",
    "V61054": "condicao_coleta_lixo",
    "V61055": "condicao_limpeza_rua",
    "V61056": "condicao_escoamento_chuva",
    "V61057": "condicao_esgotamento_sanitario",
    "V61058": "condicao_transporte_coletivo",
    "V61061": "domicilio_pouco_espaco",
    "V61062": "domicilio_pouca_iluminacao",
    "V61063": "domicilio_telhado_goteira",
    "V61064": "parede_chao_umido",
    "V61065": "janela_porta_deteriorado",
    "V61066": "problema_mosquito_inseto",
    "V61067": "problema_fumaca_barulho",
    "V61068": "domicilio_rio_poluido",
    "V61069": "area_sujeita_inundacao",
    "V610610": "domicilio_localizado_encosta",
    "V610611": "problema_violencia_area",
    "V61071": "atraso_aluguel",
    "V61072": "atraso_agua_eletricidade",
    "V61073": "atraso_prestacao_bens",
    "V6108": "preocupacao_alimentar",
    "V6109": "alimentos_acabaram",
    "V6110": "falta_recursos_alimentares",
    "V6111": "dieta_limitada",
    "V6112": "adultos_sem_refeicao",
    "V6113": "adultos_comem_menos",
    "V6114": "fome_adulta",
    "V6115": "jejum_forcado",
    "V6116": "criancas_sem_variedade",
    "V6117": "criancas_comem_menos",
    "V6118": "reducao_alimentar_infantil",
    "V6119": "criancas_sem_refeicao",
    "V6120": "fome_infantil",
    "V6121": "jejum_infantil",
    "PESO": "fator_expansao_upa",
    "PESO_FINAL": "peso_ajustado",
    "RENDA_TOTAL": "renda_bruta_uc"
}
